/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FlixcharterAffiliate {
    'apiKey': string;
    'dest': string;
    'destId': string;
    'end': string;
    'start': string;
  }
  interface FlixcharterAffiliateAttributes extends StencilHTMLAttributes {
    'apiKey'?: string;
    'dest'?: string;
    'destId'?: string;
    'end'?: string;
    'start'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FlixcharterAffiliate': Components.FlixcharterAffiliate;
  }

  interface StencilIntrinsicElements {
    'flixcharter-affiliate': Components.FlixcharterAffiliateAttributes;
  }


  interface HTMLFlixcharterAffiliateElement extends Components.FlixcharterAffiliate, HTMLStencilElement {}
  var HTMLFlixcharterAffiliateElement: {
    prototype: HTMLFlixcharterAffiliateElement;
    new (): HTMLFlixcharterAffiliateElement;
  };

  interface HTMLElementTagNameMap {
    'flixcharter-affiliate': HTMLFlixcharterAffiliateElement
  }

  interface ElementTagNameMap {
    'flixcharter-affiliate': HTMLFlixcharterAffiliateElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
